# 导入 3D 放大节点的映射
from .minimax_h3_latent_upscaler_3d import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_3D,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_3D,
)

# 导入 2D 放大节点的映射
from .minimax_h3_latent_upscaler_2d import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_2D,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_2D,
)

# 初始化合并后的字典
NODE_CLASS_MAPPINGS = {}
# 先加入 3D 节点
NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_3D)
# 再加入 2D 节点
NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_2D)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_3D)
NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_2D)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']